# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets

from src.readingsHandler import addNewRow, checkLastRowDate, deleteLastRow, editExistingRow, findRowIndexByDate, readings_dictionary
from src.plotHandler import generatePlot



class Ui_Class():
    class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(800, 176)
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
            self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 111))
            self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
            self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
            self.verticalLayout.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout.setObjectName("verticalLayout")
            self.horizontalLayout = QtWidgets.QHBoxLayout()
            self.horizontalLayout.setObjectName("horizontalLayout")
            self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
            self.pushButton.setObjectName("pushButton")
            self.horizontalLayout.addWidget(self.pushButton)
            self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
            self.pushButton_2.setObjectName("pushButton_2")
            self.horizontalLayout.addWidget(self.pushButton_2)
            self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
            self.pushButton_3.setObjectName("pushButton_3")
            self.horizontalLayout.addWidget(self.pushButton_3)
            self.verticalLayout.addLayout(self.horizontalLayout)
            self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
            self.pushButton_4.setObjectName("pushButton_4")
            self.verticalLayout.addWidget(self.pushButton_4)
            MainWindow.setCentralWidget(self.centralwidget)
            self.menubar = QtWidgets.QMenuBar(MainWindow)
            self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
            self.menubar.setObjectName("menubar")
            MainWindow.setMenuBar(self.menubar)
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            MainWindow.setStatusBar(self.statusbar)

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

            self.pushButton.clicked.connect(self.addRegister)
            self.pushButton_2.clicked.connect(self.deleteRegister)
            self.pushButton_3.clicked.connect(self.editRegister)
            self.pushButton_4.clicked.connect(self.showPlot)
        
        def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.pushButton.setText(_translate("MainWindow", "Dodaj nowe dane"))
            self.pushButton_2.setText(_translate("MainWindow", "Usuń ostatnie dane"))
            self.pushButton_3.setText(_translate("MainWindow", "Edytuj dane"))
            self.pushButton_4.setText(_translate("MainWindow", "Pokaż wykres"))

        def addRegister(self):
            dialog = QtWidgets.QDialog()
            dialog.ui = Ui_Class().Ui_AddRegisterDialog()
            dialog.ui.setupUi(dialog)
            dialog.show()
        
        def deleteRegister(self):
            dialog = QtWidgets.QDialog()
            dialog.ui = Ui_Class().Ui_DeleteRegisterDialog()
            dialog.ui.setupUi(dialog)
            dialog.show()

        def editRegister(self):
            dialog = QtWidgets.QDialog()
            dialog.ui = Ui_Class().Ui_AskForRegisterToEditDialog()
            dialog.ui.setupUi(dialog)
            dialog.show()

        def showPlot(self):
            dialog = QtWidgets.QDialog()
            dialog.ui = Ui_Class().Ui_CreatePlotDialog()
            dialog.ui.setupUi(dialog)
            dialog.show()

    class Ui_AddRegisterDialog(object):
        def setupUi(self, Dialog):
            Dialog.setObjectName("test")
            Dialog.resize(232, 226)
            self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
            self.horizontalLayout.setObjectName("horizontalLayout")
            self.verticalLayout = QtWidgets.QVBoxLayout()
            self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
            self.verticalLayout.setObjectName("verticalLayout")
            self.formLayout = QtWidgets.QFormLayout()
            self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
            self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
            self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
            self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
            self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
            self.formLayout.setHorizontalSpacing(7)
            self.formLayout.setVerticalSpacing(2)
            self.formLayout.setObjectName("formLayout")
            self.f180 = QtWidgets.QLineEdit(Dialog)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.f180.sizePolicy().hasHeightForWidth())
            self.f180.setSizePolicy(sizePolicy)
            self.f180.setObjectName("f180")
            self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.f180)
            self.f181 = QtWidgets.QLineEdit(Dialog)
            self.f181.setObjectName("f181")
            self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.f181)
            self.l181 = QtWidgets.QLabel(Dialog)
            self.l181.setObjectName("l181")
            self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.l181)
            self.f182 = QtWidgets.QLineEdit(Dialog)
            self.f182.setObjectName("f182")
            self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.f182)
            self.l182 = QtWidgets.QLabel(Dialog)
            self.l182.setEnabled(True)
            self.l182.setTabletTracking(True)
            self.l182.setObjectName("l182")
            self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.l182)
            self.f280 = QtWidgets.QLineEdit(Dialog)
            self.f280.setObjectName("f280")
            self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.f280)
            self.l280 = QtWidgets.QLabel(Dialog)
            self.l280.setObjectName("l280")
            self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.l280)
            self.f281 = QtWidgets.QLineEdit(Dialog)
            self.f281.setObjectName("f281")
            self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.f281)
            self.l281 = QtWidgets.QLabel(Dialog)
            self.l281.setObjectName("l281")
            self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.l281)
            self.f282 = QtWidgets.QLineEdit(Dialog)
            self.f282.setObjectName("f282")
            self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.f282)
            self.l282 = QtWidgets.QLabel(Dialog)
            self.l282.setObjectName("l282")
            self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.l282)
            self.l180 = QtWidgets.QLabel(Dialog)
            self.l180.setObjectName("l180")
            self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l180)
            self.verticalLayout.addLayout(self.formLayout)
            self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_2.setObjectName("horizontalLayout_2")
            self.pushButton_2 = QtWidgets.QPushButton(Dialog)
            self.pushButton_2.setObjectName("AcceptButton")
            self.horizontalLayout_2.addWidget(self.pushButton_2)
            self.pushButton = QtWidgets.QPushButton(Dialog)
            self.pushButton.setObjectName("CancelButton")
            self.horizontalLayout_2.addWidget(self.pushButton)
            self.verticalLayout.addLayout(self.horizontalLayout_2)
            self.horizontalLayout.addLayout(self.verticalLayout)

            self.retranslateUi(Dialog)
            QtCore.QMetaObject.connectSlotsByName(Dialog)

            self.pushButton.clicked.connect(lambda: self.cancelDialogOption(Dialog))
            self.pushButton_2.clicked.connect(lambda: self.acceptDialogOption(Dialog))

        def retranslateUi(self, Dialog):
            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
            self.f180.setText(_translate("Dialog", "0"))
            self.f181.setText(_translate("Dialog", "0"))
            self.l181.setText(_translate("Dialog", "1.8.1"))
            self.f182.setText(_translate("Dialog", "0"))
            self.l182.setText(_translate("Dialog", "1.8.2"))
            self.f280.setText(_translate("Dialog", "0"))
            self.l280.setText(_translate("Dialog", "2.8.0"))
            self.f281.setText(_translate("Dialog", "0"))
            self.l281.setText(_translate("Dialog", "2.8.1"))
            self.f282.setText(_translate("Dialog", "0"))
            self.l282.setText(_translate("Dialog", "2.8.2"))
            self.l180.setText(_translate("Dialog", "1.8.0"))
            self.pushButton_2.setText(_translate("Dialog", "OK"))
            self.pushButton.setText(_translate("Dialog", "Cancel"))
        
        def cancelDialogOption(self,Dialog):
            Dialog.close()

        def acceptDialogOption(self, Dialog):
            allText = self.f180.text() + self.f181.text() + self.f182.text() + self.f280.text() + self.f281.text() + self.f282.text()
            if allText.isnumeric():
                addNewRow(self.f180.text(),
                    self.f181.text(),
                    self.f182.text(),
                    self.f280.text(),
                    self.f281.text(),
                    self.f282.text(),)
                Dialog.close()
            else: 
                QMessageBox.about(Dialog, "Błąd", "Rekordy powinny być liczbami całkowitymi!")

    class Ui_DeleteRegisterDialog(object):
        def setupUi(self, Dialog):
            Dialog.setObjectName("Dialog")
            Dialog.resize(400, 103)
            self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
            self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 401, 81))
            self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
            self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
            self.verticalLayout.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout.setObjectName("verticalLayout")
            self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.label.setFont(font)
            self.label.setAlignment(QtCore.Qt.AlignCenter)
            self.label.setObjectName("label")
            self.verticalLayout.addWidget(self.label)
            self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
            self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
            self.buttonBox_2.setCenterButtons(True)
            self.buttonBox_2.setObjectName("buttonBox_2")
            self.verticalLayout.addWidget(self.buttonBox_2)

            self.retranslateUi(Dialog)
            QtCore.QMetaObject.connectSlotsByName(Dialog)

            self.buttonBox_2.rejected.connect(lambda: self.cancelDialogOption(Dialog))
            if checkLastRowDate() == "error":
                self.buttonBox_2.accepted.connect(lambda: self.cancelDialogOption(Dialog))
            else:
                self.buttonBox_2.accepted.connect(lambda: self.acceptDialogOption(Dialog))
        
        def retranslateUi(self, Dialog):
            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
            if checkLastRowDate() == "error":
                self.label.setText(_translate("Dialog", "Nie masz czego usunąć!"))
            else:
                LabelText = "Czy na pewno chcesz usunąć dane z " + checkLastRowDate() + "?"
                self.label.setText(_translate("Dialog", LabelText))

        def cancelDialogOption(self,Dialog):
            Dialog.close()
        def acceptDialogOption(self,Dialog):
            deleteLastRow()
            Dialog.close()

    class Ui_AskForRegisterToEditDialog(object):
        def setupUi(self, Dialog):
            Dialog.setObjectName("Dialog")
            Dialog.resize(401, 103)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
            Dialog.setSizePolicy(sizePolicy)
            Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
            Dialog.setAutoFillBackground(False)
            self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
            self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 401, 89))
            self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
            self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
            self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout_2.setObjectName("verticalLayout_2")
            self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
            self.label_2.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.label_2.setFont(font)
            self.label_2.setAlignment(QtCore.Qt.AlignCenter)
            self.label_2.setObjectName("label_2")
            self.verticalLayout_2.addWidget(self.label_2)
            self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
            self.lineEdit.setSizePolicy(sizePolicy)
            self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
            self.lineEdit.setAutoFillBackground(False)
            self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
            self.lineEdit.setDragEnabled(True)
            self.lineEdit.setObjectName("lineEdit")
            self.verticalLayout_2.addWidget(self.lineEdit)
            self.buttonBox_3 = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
            self.buttonBox_3.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
            self.buttonBox_3.setCenterButtons(True)
            self.buttonBox_3.setObjectName("buttonBox_3")
            self.verticalLayout_2.addWidget(self.buttonBox_3)

            self.retranslateUi(Dialog)
            QtCore.QMetaObject.connectSlotsByName(Dialog)

            self.buttonBox_3.rejected.connect(lambda: self.cancelDialogOption(Dialog))
            self.buttonBox_3.accepted.connect(lambda: self.acceptDialogOption(Dialog))

        def retranslateUi(self, Dialog):
            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
            self.label_2.setText(_translate("Dialog", "Podaj date jaką chcesz edytować"))
            self.lineEdit.setText(_translate("Dialog", "MM/YYYY"))

        def cancelDialogOption(self,Dialog):
            Dialog.close()

        def acceptDialogOption(self,Dialog):
            indexOfEditingRow = findRowIndexByDate(self.lineEdit.text())
            if indexOfEditingRow == -1:
                QMessageBox.about(Dialog, "Błąd", "Nie ma rekordu z taką datą!")
            else:
                dialog = QtWidgets.QDialog()
                dialog.ui = Ui_Class().Ui_EditRegisterDialog()
                dialog.ui.setupUi(dialog,indexOfEditingRow)
                dialog.show()
            Dialog.close()

    class Ui_EditRegisterDialog(object):
        def setupUi(self, Dialog, index):
            Dialog.setObjectName("Dialog")
            Dialog.resize(232, 226)
            self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
            self.horizontalLayout.setObjectName("horizontalLayout")
            self.verticalLayout = QtWidgets.QVBoxLayout()
            self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
            self.verticalLayout.setObjectName("verticalLayout")
            self.formLayout = QtWidgets.QFormLayout()
            self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
            self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
            self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
            self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
            self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
            self.formLayout.setHorizontalSpacing(7)
            self.formLayout.setVerticalSpacing(2)
            self.formLayout.setObjectName("formLayout")
            self.f180 = QtWidgets.QLineEdit(Dialog)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.f180.sizePolicy().hasHeightForWidth())
            self.f180.setSizePolicy(sizePolicy)
            self.f180.setObjectName("f180")
            self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.f180)
            self.f181 = QtWidgets.QLineEdit(Dialog)
            self.f181.setObjectName("f181")
            self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.f181)
            self.l181 = QtWidgets.QLabel(Dialog)
            self.l181.setObjectName("l181")
            self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.l181)
            self.f182 = QtWidgets.QLineEdit(Dialog)
            self.f182.setObjectName("f182")
            self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.f182)
            self.l182 = QtWidgets.QLabel(Dialog)
            self.l182.setEnabled(True)
            self.l182.setTabletTracking(True)
            self.l182.setObjectName("l182")
            self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.l182)
            self.f280 = QtWidgets.QLineEdit(Dialog)
            self.f280.setObjectName("f280")
            self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.f280)
            self.l280 = QtWidgets.QLabel(Dialog)
            self.l280.setObjectName("l280")
            self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.l280)
            self.f281 = QtWidgets.QLineEdit(Dialog)
            self.f281.setObjectName("f281")
            self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.f281)
            self.l281 = QtWidgets.QLabel(Dialog)
            self.l281.setObjectName("l281")
            self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.l281)
            self.f282 = QtWidgets.QLineEdit(Dialog)
            self.f282.setObjectName("f282")
            self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.f282)
            self.l282 = QtWidgets.QLabel(Dialog)
            self.l282.setObjectName("l282")
            self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.l282)
            self.l180 = QtWidgets.QLabel(Dialog)
            self.l180.setObjectName("l180")
            self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l180)
            self.verticalLayout.addLayout(self.formLayout)
            self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_2.setObjectName("horizontalLayout_2")
            self.pushButton_2 = QtWidgets.QPushButton(Dialog)
            self.pushButton_2.setObjectName("pushButton_2")
            self.horizontalLayout_2.addWidget(self.pushButton_2)
            self.pushButton = QtWidgets.QPushButton(Dialog)
            self.pushButton.setObjectName("pushButton")
            self.horizontalLayout_2.addWidget(self.pushButton)
            self.verticalLayout.addLayout(self.horizontalLayout_2)
            self.horizontalLayout.addLayout(self.verticalLayout)

            self.retranslateUi(Dialog, index)
            QtCore.QMetaObject.connectSlotsByName(Dialog)

            self.pushButton.clicked.connect(lambda: self.cancelDialogOption(Dialog))
            self.pushButton_2.clicked.connect(lambda: self.AcceptDialogOption(Dialog, index))

        def retranslateUi(self, Dialog, index):
            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
            self.f180.setText(_translate("Dialog", readings_dictionary[index]['1.8.0']))
            self.f181.setText(_translate("Dialog", readings_dictionary[index]['1.8.1']))
            self.l181.setText(_translate("Dialog", "1.8.1"))
            self.f182.setText(_translate("Dialog", readings_dictionary[index]['1.8.2']))
            self.l182.setText(_translate("Dialog", "1.8.2"))
            self.f280.setText(_translate("Dialog", readings_dictionary[index]['2.8.0']))
            self.l280.setText(_translate("Dialog", "2.8.0"))
            self.f281.setText(_translate("Dialog", readings_dictionary[index]['2.8.1']))
            self.l281.setText(_translate("Dialog", "2.8.1"))
            self.f282.setText(_translate("Dialog", readings_dictionary[index]['2.8.2']))
            self.l282.setText(_translate("Dialog", "2.8.2"))
            self.l180.setText(_translate("Dialog", "1.8.0"))
            self.pushButton_2.setText(_translate("Dialog", "OK"))
            self.pushButton.setText(_translate("Dialog", "Cancel"))

        def cancelDialogOption(self,Dialog):
            Dialog.close()

        def AcceptDialogOption(self, Dialog, index):
            editExistingRow(index,
                self.f180.text(),
                self.f181.text(),
                self.f182.text(),
                self.f280.text(),
                self.f281.text(),
                self.f282.text(),)
            Dialog.close()

    class Ui_CreatePlotDialog(object):
        def setupUi(self, Dialog):
            Dialog.setObjectName("Dialog")
            Dialog.resize(427, 264)
            self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
            self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 421, 261))
            self.gridLayoutWidget.setObjectName("gridLayoutWidget")
            self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
            self.gridLayout.setContentsMargins(0, 0, 0, 0)
            self.gridLayout.setObjectName("gridLayout")
            self.checkBox_6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
            self.checkBox_6.setObjectName("checkBox_6")
            self.gridLayout.addWidget(self.checkBox_6, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
            self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
            self.checkBox_4.setObjectName("checkBox_4")
            self.gridLayout.addWidget(self.checkBox_4, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
            self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
            self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
            self.buttonBox.setCenterButtons(True)
            self.buttonBox.setObjectName("buttonBox")
            self.gridLayout.addWidget(self.buttonBox, 8, 0, 1, 1)
            self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
            self.checkBox_3.setObjectName("checkBox_3")
            self.gridLayout.addWidget(self.checkBox_3, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
            self.horizontalLayout = QtWidgets.QHBoxLayout()
            self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
            self.horizontalLayout.setSpacing(0)
            self.horizontalLayout.setObjectName("horizontalLayout")
            self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
            self.lineEdit_2.setSizePolicy(sizePolicy)
            self.lineEdit_2.setObjectName("lineEdit_2")
            self.horizontalLayout.addWidget(self.lineEdit_2)
            self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
            self.lineEdit.setSizePolicy(sizePolicy)
            self.lineEdit.setObjectName("lineEdit")
            self.horizontalLayout.addWidget(self.lineEdit)
            self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
            self.checkBox_5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
            self.checkBox_5.setObjectName("checkBox_5")
            self.gridLayout.addWidget(self.checkBox_5, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
            self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
            self.checkBox.setTristate(False)
            self.checkBox.setObjectName("checkBox")
            self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
            self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
            self.checkBox_2.setObjectName("checkBox_2")
            self.gridLayout.addWidget(self.checkBox_2, 7, 0, 1, 1, QtCore.Qt.AlignHCenter)

            self.retranslateUi(Dialog)
            QtCore.QMetaObject.connectSlotsByName(Dialog)

            self.buttonBox.rejected.connect(lambda: self.cancelDialogOption(Dialog))
            self.buttonBox.accepted.connect(lambda: self.acceptDialogOption(Dialog))

        def retranslateUi(self, Dialog):
            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
            self.checkBox_6.setText(_translate("Dialog", "1.8.1"))
            self.checkBox_4.setText(_translate("Dialog", "2.8.0"))
            self.checkBox_3.setText(_translate("Dialog", "2.8.1"))
            self.lineEdit_2.setText(_translate("Dialog", "StartDate"))
            self.lineEdit.setText(_translate("Dialog", "EndDate"))
            self.checkBox_5.setText(_translate("Dialog", "1.8.2"))
            self.checkBox.setText(_translate("Dialog", "1.8.0"))
            self.checkBox_2.setText(_translate("Dialog", "2.8.2"))

        def cancelDialogOption(self,Dialog):
            Dialog.close()

        def acceptDialogOption(self,Dialog):
            indexOfStartRow = findRowIndexByDate(self.lineEdit_2.text())
            indexOfEndRow = findRowIndexByDate(self.lineEdit.text())
            if indexOfStartRow == -1 or indexOfEndRow == -1:
                if indexOfStartRow == -1:
                    QMessageBox.about(Dialog, "Błąd", "Nie ma rekordu z taką początkową datą!")
                else: 
                    QMessageBox.about(Dialog, "Błąd", "Nie ma rekordu z taką końcową datą!")
            elif indexOfStartRow > indexOfEndRow:
                QMessageBox.about(Dialog, "Błąd", "Data końcowa nie może być wcześniej od początkowej!")
            else: 
                anyCheckOn = False
                anyCheckOn = self.checkBox.isChecked() or self.checkBox_2.isChecked() or self.checkBox_3.isChecked() or self.checkBox_4.isChecked() or self.checkBox_5.isChecked() or self.checkBox_6.isChecked()

                if anyCheckOn == False:
                    QMessageBox.about(Dialog, "Błąd", "Musisz zaznaczyć cokolwiek!")
                else:
                    boolList = [self.checkBox.isChecked(),
                                self.checkBox_6.isChecked(),
                                self.checkBox_5.isChecked(),
                                self.checkBox_4.isChecked(),
                                self.checkBox_3.isChecked(),
                                self.checkBox_2.isChecked()]
                    generatePlot(indexOfStartRow,indexOfEndRow,boolList)

